defmodule Lang.Dev.DocRenderer do
  @moduledoc """
  Deterministic Markdown renderer for JSON‑LD models (dev‑only).

  - Produces Markdown with a YAML frontmatter block containing model metadata.
  - Rendering aims to be stable for CI diffing and drift detection.
  - Writes files under `priv/docs/rendered/<model_id>.md`.

  Notes
  - Per guidelines, filesystem operations prefer native NIFs. Since writing isn't
    exposed by FSScanner, we carefully use Elixir's File module for writes and
    directory creation with defensive error handling.
  """

  alias Lang.Dev.JSONLDHelper
  require Logger

  @doc_path ["priv", "docs", "rendered"]

  @type meta :: %{
          required(:id) => String.t(),
          required(:version) => String.t(),
          required(:hash) => String.t(),
          required(:provenance) => String.t(),
          optional(:generated_by) => String.t(),
          optional(:rendered_at) => DateTime.t()
        }

  @spec output_dir() :: String.t()
  def output_dir, do: Lang.Dev.Config.docs_dir()

  @doc """
  Render a JSON‑LD map + metadata to a deterministic Markdown string.
  """
  @spec render_markdown(map(), meta()) :: String.t()
  def render_markdown(model_map, %{id: id, version: version, hash: hash, provenance: prov} = meta)
      when is_map(model_map) do
    generated_by = Map.get(meta, :generated_by, app_version())
    rendered_at = Map.get(meta, :rendered_at, DateTime.utc_now())

    # Stable YAML frontmatter generation (manual, fixed order)
    fm =
      [
        "---",
        ~s/id: "#{escape_yaml(id)}"/,
        ~s/version: "#{escape_yaml(version)}"/,
        ~s/hash: "#{escape_yaml(hash)}"/,
        ~s/provenance: "#{escape_yaml(prov)}"/,
        ~s/generated_by: "#{escape_yaml(generated_by)}"/,
        ~s/rendered_at: "#{escape_yaml(DateTime.to_iso8601(rendered_at))}"/,
        "---"
      ]
      |> Enum.join("\n")

    # Deterministic, pretty JSON block of the model payload
    pretty_json = Jason.encode!(model_map, pretty: true)

    body = [
      "# Model: #{id}",
      "",
      "Metadata",
      "",
      "- ID: #{Lang.Dev.SafeText.sanitize(id)}",
      "- Version: #{Lang.Dev.SafeText.sanitize(version)}",
      "- Hash: #{Lang.Dev.SafeText.sanitize(hash)}",
      "- Provenance: #{Lang.Dev.SafeText.sanitize(prov)}",
      "- Generated By: #{Lang.Dev.SafeText.sanitize(generated_by)}",
      "- Rendered At: #{Lang.Dev.SafeText.sanitize(DateTime.to_iso8601(rendered_at))}",
      "",
      "## JSON‑LD",
      "",
      "````json",
      pretty_json,
      "````"
    ]
    |> Enum.join("\n")

    [fm, body] |> Enum.join("\n\n")
  end

  @doc """
  Write the rendered markdown to the output directory. Returns the path.
  """
  @spec write_markdown(String.t(), String.t()) :: {:ok, String.t()} | {:error, term()}
  def write_markdown(model_id, markdown) when is_binary(model_id) and is_binary(markdown) do
    dir = output_dir()
    :ok = ensure_dir(dir)
    path = Path.join(dir, "#{safe_filename(model_id)}.md")

    case File.write(path, markdown) do
      :ok -> {:ok, path}
      {:error, reason} -> {:error, reason}
    end
  end

  @doc """
  Parse a rendered markdown file and return {frontmatter_map, remaining_content}.
  Strict but minimal YAML frontmatter parser that expects a fixed layout with
  quoted string values.
  """
  @spec parse_frontmatter(String.t()) :: {:ok, map(), String.t()} | {:error, term()}
  def parse_frontmatter(markdown) when is_binary(markdown) do
    case String.split(markdown, "\n", parts: 2) do
      ["---" <> _ = _first_line | _] -> do_parse_frontmatter(markdown)
      _ -> {:error, :missing_frontmatter}
    end
  end

  defp do_parse_frontmatter(markdown) do
    # Split at the second delimiter
    case String.split(markdown, "\n---\n", parts: 2) do
      [<<"---\n", _::binary>> = front_block, rest] ->
        yaml = String.replace_prefix(front_block, "---\n", "")
        fm =
          yaml
          |> String.split("\n")
          |> Enum.reduce(%{}, fn line, acc ->
            case String.split(line, ": ", parts: 2) do
              [k, v] -> Map.put(acc, k, strip_quotes(v))
              _ -> acc
            end
          end)
        {:ok, fm, rest}
      _ -> {:error, :invalid_frontmatter}
    end
  end

  defp strip_quotes(nil), do: nil
  defp strip_quotes(<<"\"", rest::binary>>) do
    rest |> String.trim_trailing("\"")
  end
  defp strip_quotes(v), do: v

  @doc """
  Extracts the first JSON code block (```json ... ```) and decodes it.
  Returns {:ok, map} or {:error, reason}.
  """
  @spec extract_json(String.t()) :: {:ok, map()} | {:error, term()}
  def extract_json(content) when is_binary(content) do
    # Support both triple and quadruple backtick fences, prefer quadruple
    with {:error, _} <- extract_json_with(content, "````json\n", "\n````"),
         {:error, _} <- extract_json_with(content, "```json\n", "\n```") do
      {:error, :json_block_not_found}
    else
      {:ok, map} -> {:ok, map}
      other -> other
    end
  end

  defp extract_json_with(content, open, close) do
    case String.split(content, open, parts: 2) do
      [_, rest] ->
        case String.split(rest, close, parts: 2) do
          [json_text, _] ->
            try do
              {:ok, Jason.decode!(json_text)}
            rescue
              _ -> {:error, :invalid_json_block}
            end
          _ -> {:error, :json_block_not_found}
        end
      _ -> {:error, :json_block_not_found}
    end
  end

  defp ensure_dir(dir) do
    case File.mkdir_p(dir) do
      :ok -> :ok
      {:error, :eexist} -> :ok
      {:error, reason} -> raise "failed to create docs dir #{dir}: #{inspect(reason)}"
    end
  end

  defp safe_filename(id) do
    id
    |> String.replace(~r/[^a-zA-Z0-9_\-\.]+/, "-")
    |> String.trim("-")
  end

  defp app_version do
    case :application.get_key(:lang, :vsn) do
      {:ok, vsn} when is_list(vsn) -> to_string(vsn)
      {:ok, vsn} -> to_string(vsn)
      _ -> "dev"
    end
  end

  defp escape_yaml(str) when is_binary(str) do
    str
    |> Lang.Dev.SafeText.sanitize()
    |> String.replace("\"", "\\\"")
  end
end

