import Config

# Configure your database
config :lang, Lang.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "lang_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# Performance monitoring and profiling for LANG development
config :ash_profiler, :enabled, true
config :ash_profiler, :report_threshold_ms, 100
config :ash_profiler, :log_slow_queries, true
config :ash_profiler, :track_memory_usage, true

# Enable telemetry for performance monitoring
config :telemetry_poller,
  measurements: [
    # VM Measurements
    {[:vm, :memory], :total},
    {[:vm, :memory], :processes},
    {[:vm, :memory], :atoms},
    {[:vm, :memory], :binary},
    {[:vm, :memory], :code},
    {[:vm, :memory], :ets},

    # System Measurements
    {:system_counts, :process_count},
    {:system_counts, :atom_count},
    {:system_counts, :port_count},

    # LANG-specific measurements
    {:lang_metrics, :native_nif_calls},
    {:lang_metrics, :ash_query_count},
    {:lang_metrics, :oban_job_count}
  ]

# LANG Performance Monitoring Configuration
config :lang, :performance,
  # Enable performance monitoring in development
  enabled: true,
  # Profile Ash operations slower than 50ms
  slow_query_threshold: 50,
  # Track memory usage for native NIFs
  track_nif_memory: true,
  # Monitor Oban job performance
  monitor_background_jobs: true,
  # Profile filesystem operations
  profile_native_operations: true

# Native NIF Performance Tracking
config :lang, :native_profiling,
  track_fs_scanner: true,
  track_text_analysis: true,
  track_graph_reasoner: true,
  memory_sampling_interval: 1000

# Oban Performance Monitoring
config :lang, Oban,
  repo: Lang.Repo,
  plugins: [
    # Telemetry is built-in to Oban - no plugin needed
    Oban.Plugins.Pruner,
    {Oban.Plugins.Cron,
     crontab: [
       # Performance monitoring tasks
       {"*/5 * * * *", Lang.Workers.PerformanceMetricsWorker, queue: :metrics, max_attempts: 1}
     ]}
  ],
  queues: [
    default: 5,
    analysis: 3,
    lsp: 10,
    metrics: 2,
    cleanup: 1
  ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :lang, LangWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "4RuMdAMpZw8Mai1W/wMhw98lYHHpkLXXlzSdqRpzy8fsIaUvCSABfvArl3RQ+h8z",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:lang, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:lang, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :lang, LangWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/lang_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :lang, dev_routes: true

config :lang, :fswatcher_logger, topic: "dev:fs:jsonld", level: :debug

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Add Ash optimizations for fast compilation
config :ash, :disable_compile_time_validations?, true
config :ash, :compile_time_index?, false

# Optimize logging for development
config :logger, level: :info

config :rustler_precompiled, :force_build, lang: true

# Stripe configuration for development
# Use test keys in development - these are safe to commit
config :stripity_stripe,
  api_key: System.get_env("STRIPE_SECRET_KEY", "sk_test_51234567890abcdefghijklmnopqrstuvwxyz"),
  public_key:
    System.get_env("STRIPE_PUBLISHABLE_KEY", "pk_test_51234567890abcdefghijklmnopqrstuvwxyz")

config :lang, :stripe,
  webhook_secret:
    System.get_env("STRIPE_WEBHOOK_SECRET", "whsec_test_webhook_secret_for_development"),
  success_url: "http://localhost:4000/billing?success=true",
  cancel_url: "http://localhost:4000/billing?cancelled=true",
  price_ids: %{
    plus: System.get_env("STRIPE_PLUS_PRICE_ID", "price_test_plus_placeholder"),
    pro: System.get_env("STRIPE_PRO_PRICE_ID", "price_test_pro_placeholder"),
    business: System.get_env("STRIPE_BUSINESS_PRICE_ID", "price_test_business_placeholder")
  }
