defmodule Lang.Repo.Migrations.AddLspAnalyticsTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:spatial_waypoints) do
      remove :tags
      remove :position
      remove :path
    end

    drop constraint(:spatial_waypoints, "spatial_waypoints_project_id_fkey")

    alter table(:spatial_waypoints) do
      modify :project_id, :text, null: false
      add :file, :text
      add :line, :bigint
    end

    create index(:spatial_waypoints, [:project_id])

    drop constraint(:spatial_paths, "spatial_paths_project_id_fkey")

    alter table(:spatial_paths) do
      modify :rationale, :text, default: nil
      modify :hops, :bigint, default: 1
      modify :project_id, :text, null: false
      add :from_label, :text
      add :to_label, :text
      add :metadata, :map, default: %{}
    end

    create index(:spatial_paths, [:project_id])

    drop constraint(:spatial_maps, "spatial_maps_project_id_fkey")

    alter table(:spatial_maps) do
      modify :stats, :map, null: true
      modify :graph_summary, :map, null: true
      modify :project_id, :text, null: false
    end

    create index(:spatial_maps, [:project_id])
  end

  def down do
    drop_if_exists index(:spatial_maps, [:project_id])

    alter table(:spatial_maps) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "spatial_maps_project_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true

      modify :graph_summary, :map, null: false
      modify :stats, :map, null: false
    end

    drop_if_exists index(:spatial_paths, [:project_id])

    alter table(:spatial_paths) do
      remove :metadata
      remove :to_label
      remove :from_label

      modify :project_id,
             references(:projects,
               column: :id,
               name: "spatial_paths_project_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true

      modify :hops, {:array, :map}, default: []
      modify :rationale, :map, default: %{}
    end

    drop_if_exists index(:spatial_waypoints, [:project_id])

    alter table(:spatial_waypoints) do
      remove :line
      remove :file

      modify :project_id,
             references(:projects,
               column: :id,
               name: "spatial_waypoints_project_id_fkey",
               type: :uuid,
               prefix: "public"
             ),
             null: true
    end

    alter table(:spatial_waypoints) do
      add :path, :text
      add :position, :map, default: %{}
      add :tags, {:array, :text}, default: []
    end
  end
end
