defmodule Lang.Repo.Migrations.AddTokenOptimizationTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:violations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :rule_id, :text, null: false
      add :rule_name, :text, null: false
      add :rule_category, :text
      add :severity, :text, null: false
      add :status, :text, null: false, default: "open"
      add :message, :text, null: false
      add :description, :text
      add :fix_suggestion, :text
      add :line_number, :bigint
      add :column_number, :bigint
      add :line_content, :text
      add :impact_assessment, :text
      add :compliance_tags, {:array, :text}, null: false, default: []
      add :confidence_score, :decimal
      add :metadata, :map, null: false, default: %{}
      add :resolved_at, :utc_datetime
      add :resolved_by, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :analyzed_file_id, :uuid
    end

    create table(:token_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :summary, :text
      add :token_count, :bigint
      add :optimized_token_count, :bigint
      add :compression_ratio, :decimal
      add :model_estimates, :map, null: false, default: %{}
      add :optimized_content, :text
      add :relevance_scores, {:array, :map}, null: false, default: []
      add :streaming_deltas, {:array, :map}, null: false, default: []
      add :cache_recommendations, :map, null: false, default: %{}
      add :details, :map, null: false, default: %{}
      add :artifacts, {:array, :map}, null: false, default: []
      add :confidence_score, :decimal
      add :metrics, :map, null: false, default: %{}
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :request_id, :uuid
    end

    create table(:token_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:token_results) do
      modify :request_id,
             references(:token_requests,
               column: :id,
               name: "token_results_request_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:token_requests) do
      add :kind, :text, null: false
      add :input, :map, null: false, default: %{}
      add :model_type, :text
      add :target_ratio, :decimal
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :metadata, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "token_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_id, :uuid
      add :run_id, :uuid
    end

    create table(:think_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :summary, :text
      add :details, :map, null: false, default: %{}
      add :artifacts, {:array, :map}, null: false, default: []
      add :confidence_score, :decimal
      add :metrics, :map, null: false, default: %{}
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :request_id, :uuid
    end

    create table(:think_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:think_results) do
      modify :request_id,
             references(:think_requests,
               column: :id,
               name: "think_results_request_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:think_requests) do
      add :kind, :text, null: false
      add :input, :map, null: false, default: %{}
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :metadata, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "think_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_id, :uuid
      add :run_id, :uuid
    end

    create table(:spatial_waypoints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :label, :text
      add :path, :text
      add :position, :map, default: %{}
      add :tags, {:array, :text}, default: []
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid
    end

    create table(:spatial_paths, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :from_ref, :text
      add :to_ref, :text
      add :hops, {:array, :map}, default: []
      add :rationale, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid
    end

    create table(:spatial_maps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :graph_summary, :map, null: false, default: %{}
      add :stats, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid
    end

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:token_requests) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "token_requests_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:think_requests) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "think_requests_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:spatial_waypoints) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "spatial_waypoints_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:spatial_paths) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "spatial_paths_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:spatial_maps) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "spatial_maps_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:projects) do
      add :name, :text, null: false
      add :description, :text
      add :repository_url, :text
      add :language, :text
      add :framework, :text
      add :project_type, :text, null: false, default: "web_app"
      add :status, :text, null: false, default: "active"
      add :settings, :map, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "projects_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create unique_index(:projects, [:user_id, :name], name: "projects_unique_name_per_user_index")

    create table(:generate_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :strategy, :text, null: false
      add :inputs, :map, null: false, default: %{}
      add :boundaries, :map, null: false, default: %{}
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :metadata, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "generate_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_id,
          references(:projects,
            column: :id,
            name: "generate_requests_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :run_id, :uuid
    end

    create table(:generate_artifacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :path, :text
      add :language, :text
      add :change_type, :text, null: false, default: "create"
      add :patch, :text
      add :vfs_uri, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :request_id,
          references(:generate_requests,
            column: :id,
            name: "generate_artifacts_request_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:analyzed_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:violations) do
      modify :analyzed_file_id,
             references(:analyzed_files,
               column: :id,
               name: "violations_analyzed_file_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:analyzed_files) do
      add :file_path, :text, null: false
      add :file_name, :text, null: false
      add :file_extension, :text
      add :file_size_bytes, :bigint
      add :content_type, :text
      add :language_detected, :text
      add :content_hash, :text
      add :vfs_uri, :text
      add :content, :text
      add :status, :text, null: false, default: "pending"
      add :analysis_result, :map, null: false, default: %{}
      add :processed_at, :utc_datetime
      add :processing_time_ms, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :workspace_id, :uuid
      add :analysis_session_id, :uuid
    end

    create table(:analysis_sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:token_requests) do
      modify :run_id,
             references(:analysis_sessions,
               column: :id,
               name: "token_requests_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:think_requests) do
      modify :run_id,
             references(:analysis_sessions,
               column: :id,
               name: "think_requests_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:generate_requests) do
      modify :run_id,
             references(:analysis_sessions,
               column: :id,
               name: "generate_requests_run_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:analyzed_files) do
      modify :analysis_session_id,
             references(:analysis_sessions,
               column: :id,
               name: "analyzed_files_analysis_session_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:analysis_sessions) do
      add :status, :text, null: false, default: "pending"
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime
      add :file_count, :bigint, null: false, default: 0
      add :total_size_bytes, :bigint, null: false, default: 0
      add :violations_count, :bigint, null: false, default: 0
      add :critical_issues_count, :bigint, null: false, default: 0
      add :warnings_count, :bigint, null: false, default: 0
      add :processing_time_ms, :bigint
      add :metadata, :map, null: false, default: %{}
      add :error_message, :text
      add :workspace_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "analysis_sessions_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:analysis_sessions, "analysis_sessions_project_id_fkey")

    alter table(:analysis_sessions) do
      remove :project_id
      remove :updated_at
      remove :inserted_at
      remove :workspace_id
      remove :error_message
      remove :metadata
      remove :processing_time_ms
      remove :warnings_count
      remove :critical_issues_count
      remove :violations_count
      remove :total_size_bytes
      remove :file_count
      remove :completed_at
      remove :started_at
      remove :status
    end

    drop constraint(:analyzed_files, "analyzed_files_analysis_session_id_fkey")

    alter table(:analyzed_files) do
      modify :analysis_session_id, :uuid
    end

    drop constraint(:generate_requests, "generate_requests_run_id_fkey")

    alter table(:generate_requests) do
      modify :run_id, :uuid
    end

    drop constraint(:think_requests, "think_requests_run_id_fkey")

    alter table(:think_requests) do
      modify :run_id, :uuid
    end

    drop constraint(:token_requests, "token_requests_run_id_fkey")

    alter table(:token_requests) do
      modify :run_id, :uuid
    end

    drop table(:analysis_sessions)

    alter table(:analyzed_files) do
      remove :analysis_session_id
      remove :workspace_id
      remove :updated_at
      remove :inserted_at
      remove :processing_time_ms
      remove :processed_at
      remove :analysis_result
      remove :status
      remove :content
      remove :vfs_uri
      remove :content_hash
      remove :language_detected
      remove :content_type
      remove :file_size_bytes
      remove :file_extension
      remove :file_name
      remove :file_path
    end

    drop constraint(:violations, "violations_analyzed_file_id_fkey")

    alter table(:violations) do
      modify :analyzed_file_id, :uuid
    end

    drop table(:analyzed_files)

    drop constraint(:generate_artifacts, "generate_artifacts_request_id_fkey")

    drop table(:generate_artifacts)

    drop constraint(:generate_requests, "generate_requests_user_id_fkey")

    drop constraint(:generate_requests, "generate_requests_project_id_fkey")

    drop table(:generate_requests)

    drop_if_exists unique_index(:projects, [:user_id, :name],
                     name: "projects_unique_name_per_user_index"
                   )

    drop constraint(:projects, "projects_user_id_fkey")

    alter table(:projects) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :settings
      remove :status
      remove :project_type
      remove :framework
      remove :language
      remove :repository_url
      remove :description
      remove :name
    end

    drop constraint(:spatial_maps, "spatial_maps_project_id_fkey")

    alter table(:spatial_maps) do
      modify :project_id, :uuid
    end

    drop constraint(:spatial_paths, "spatial_paths_project_id_fkey")

    alter table(:spatial_paths) do
      modify :project_id, :uuid
    end

    drop constraint(:spatial_waypoints, "spatial_waypoints_project_id_fkey")

    alter table(:spatial_waypoints) do
      modify :project_id, :uuid
    end

    drop constraint(:think_requests, "think_requests_project_id_fkey")

    alter table(:think_requests) do
      modify :project_id, :uuid
    end

    drop constraint(:token_requests, "token_requests_project_id_fkey")

    alter table(:token_requests) do
      modify :project_id, :uuid
    end

    drop table(:projects)

    drop table(:spatial_maps)

    drop table(:spatial_paths)

    drop table(:spatial_waypoints)

    drop constraint(:think_requests, "think_requests_user_id_fkey")

    alter table(:think_requests) do
      remove :run_id
      remove :project_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :started_at
      remove :metadata
      remove :error_message
      remove :status
      remove :input
      remove :kind
    end

    drop constraint(:think_results, "think_results_request_id_fkey")

    alter table(:think_results) do
      modify :request_id, :uuid
    end

    drop table(:think_requests)

    drop table(:think_results)

    drop constraint(:token_requests, "token_requests_user_id_fkey")

    alter table(:token_requests) do
      remove :run_id
      remove :project_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :started_at
      remove :metadata
      remove :error_message
      remove :status
      remove :target_ratio
      remove :model_type
      remove :input
      remove :kind
    end

    drop constraint(:token_results, "token_results_request_id_fkey")

    alter table(:token_results) do
      modify :request_id, :uuid
    end

    drop table(:token_requests)

    drop table(:token_results)

    drop table(:violations)
  end
end
