defmodule Lang.Repo.Migrations.AddMachine do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:query_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :summary, :text
      add :answer, :text
      add :confidence_score, :decimal
      add :code_locations, {:array, :map}, null: false, default: []
      add :affected_systems, {:array, :map}, null: false, default: []
      add :dependency_graph, :map, null: false, default: %{}
      add :ownership_info, {:array, :map}, null: false, default: []
      add :risk_assessment, :map, null: false, default: %{}
      add :graph_reasoning, :map, null: false, default: %{}
      add :knowledge_entities, {:array, :map}, null: false, default: []
      add :search_results, {:array, :map}, null: false, default: []
      add :recommendations, {:array, :text}, null: false, default: []
      add :details, :map, null: false, default: %{}
      add :artifacts, {:array, :map}, null: false, default: []
      add :provider_used, :text
      add :processing_method, :text
      add :metrics, :map, null: false, default: %{}
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :request_id, :uuid
    end

    create table(:query_requests, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:query_results) do
      modify :request_id,
             references(:query_requests,
               column: :id,
               name: "query_results_request_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:query_requests) do
      add :kind, :text, null: false
      add :query, :text, null: false
      add :context, :map, null: false, default: %{}
      add :scope, :text
      add :target_element, :text
      add :change_description, :text
      add :analysis_depth, :text, null: false, default: "standard"
      add :use_graph_reasoning, :boolean, null: false, default: true
      add :provider_preference, :text
      add :status, :text, null: false, default: "pending"
      add :error_message, :text
      add :metadata, :map, null: false, default: %{}
      add :started_at, :utc_datetime
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "query_requests_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :project_id,
          references(:projects,
            column: :id,
            name: "query_requests_project_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :run_id,
          references(:analysis_sessions,
            column: :id,
            name: "query_requests_run_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:query_requests, "query_requests_user_id_fkey")

    drop constraint(:query_requests, "query_requests_project_id_fkey")

    drop constraint(:query_requests, "query_requests_run_id_fkey")

    alter table(:query_requests) do
      remove :run_id
      remove :project_id
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :started_at
      remove :metadata
      remove :error_message
      remove :status
      remove :provider_preference
      remove :use_graph_reasoning
      remove :analysis_depth
      remove :change_description
      remove :target_element
      remove :scope
      remove :context
      remove :query
      remove :kind
    end

    drop constraint(:query_results, "query_results_request_id_fkey")

    alter table(:query_results) do
      modify :request_id, :uuid
    end

    drop table(:query_requests)

    drop table(:query_results)
  end
end
